ui:
  ssl: false
  host: 0.0.0.0
  port: 8081
  nameSpace: /
  baseUrl: http://localhost:8081
  useProxies: true

rest:
  ssl: false
  host: localhost
  port: 8081
  nameSpace: /server

themes:
  - name: dspace
    headTags:
      - tagName: link
        attributes:
          rel: icon
          href: assets/dspace/images/favicons/favicon.ico
          sizes: any
      - tagName: link
        attributes:
          rel: icon
          href: assets/dspace/images/favicons/favicon.svg
          type: image/svg+xml
      - tagName: link
        attributes:
          rel: manifest
          href: assets/dspace/images/favicons/manifest.webmanifest
